import { CliUsageError } from "./errors.js";
import { parseCommand } from "./parse-args.js";
import { searchIndex } from "./search-index.js";

export const HELP = `hackathon-atlas search --index <generated.sqlite> [--filter field=value] <keywords>

Search a SQLite FTS5 index generated by @hackathon-atlas/catalog-index.

Options:
  --index, -i <path>         Generated SQLite index. Required for search.
  --filter, -f <field>=<value>
                             Repeatable. Applied only when <field> is a column
                             of the records table. If that column is absent,
                             the filter is not applied and its status is unknown.
  -h, --help                 Show this help.

hitCounts.real is the number of matching rows stored with synthetic false.
Rows stored with synthetic true are counted only under hitCounts.synthetic.
If the index has no synthetic column, those counts are unknown and the rows
are not reported as real.

This command does not call a language model, does not use a vector database,
and does not create catalog records.
`;

export type CliIo = {
  stdout: (chunk: string) => void;
  stderr: (chunk: string) => void;
};

const defaultIo: CliIo = {
  stdout: (chunk) => {
    process.stdout.write(chunk);
  },
  stderr: (chunk) => {
    process.stderr.write(chunk);
  },
};

export function runCli(argv: readonly string[], io: CliIo = defaultIo): number {
  try {
    const command = parseCommand(argv);
    if (command.kind === "help") {
      io.stdout(HELP);
      return 0;
    }
    const result = searchIndex(command);
    for (const filter of result.filters) {
      if (!filter.applied && filter.reason !== null) {
        io.stderr(`Filter ${filter.field} was not applied. Status: unknown. ${filter.reason}\n`);
      }
    }
    if (result.hitCounts.status === "unknown" && result.hitCounts.reason !== null) {
      io.stderr(`${result.hitCounts.reason}\n`);
    } else if (result.hitCounts.synthetic !== null && result.hitCounts.synthetic > 0) {
      io.stderr(
        "Synthetic hits are labeled synthetic and are excluded from hitCounts.real.\n",
      );
    }
    io.stdout(`${JSON.stringify(result, null, 2)}\n`);
    return 0;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    io.stderr(`error: ${message}\n`);
    if (error instanceof CliUsageError) {
      return 2;
    }
    return 1;
  }
}
